@startuml ModelSpec
package de.thro.inf.prg3.a06.model {
    +class Joke {

        -number: int
        -content: String
        -rubrics: String[]

        +getNumber(): int
        +setNumber(number: int): void
        +getContent(): String
        +setContent(content: String): void
        +getRubrics(): String[]
        +setRubrics(rubrics: String[]): void
    }
}
@enduml